name: AfkRoom
version: '${project.version}'
main: xyz.mlserver.afkroom.AFKRoom

depend:
    - AFKPlus

commands:
    afkroom:
        description: Teleport to the AFK room
        usage: /afkroom
        permission: afkroom.setroom